version: '3.8'

name: 'fakeflix'

services:
  db:
    image: postgres:18-alpine
    container_name: fakeflix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fakeflix-db
    volumes:
      - .data:/var/lib/postgresql/18/docker
    ports:
      - '5432:5432'
